name: Cypress API Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar Dependências e Rodar Testes
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
        env:
          # O GitHub pega o segredo 'CYPRESS_TOKEN' das Configurações 
          # e entrega para o código como Cypress.env('TOKEN')
          CYPRESS_TOKEN: ${{ secrets.CYPRESS_TOKEN }}

      - name: Upload de Relatórios (Vídeos/Screenshots)
        uses: actions/upload-artifact@v4
        if: failure() # Só gera o download se o teste falhar
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos